exec_once:
 execs:
  Get dokuwiki source:
   name: Get dokuwiki source
   command: |
     wget -qO- https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz | tar xvz  -C . --strip 1

post_app_deploy:
 execs:
  Restart apache:
   name: Restart apache
   command: |
     #!/usr/bin/env bash
     chown -RL www-data:www-data /var/www/html/dokuwiki
     service apache2 restart
